export const pagelist = {
  intro: [
    'preparation',
    'characters',
    'vowels',
    {
      consonants: [
        'kvowels',
        'svowels',
        'tvowels',
        'nvowels',
        'hvowels',
        'mvowels',
        'yvowels',
        'rvowels',
        'wvowels',
        'n',
        'fiftysoundstable',
        'gvowels',
        'zvowels',
        'dvowels',
        'bvowels',
        'pvowels',
        'kyvowels',
        'shvowels',
        'chvowels',
        'nyvowels',
        'hyvowels',
        'myvowels',
        'ryvowels',
        'gyvowels',
        'jvowels',
        'byvowels',
        'pyvowels',
      ],
    },
  ],
};
